steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'  # Specify the Docker builder image
    args: ['build', '-t', 'gcr.io/glass-oath-344412/video-ai-search:$COMMIT_SHA', 'video-ai-search/.']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'  # Specify the Docker builder image
    args: ['push', 'gcr.io/glass-oath-344412/video-ai-search:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'  # Specify the Cloud SDK image for gcloud commands
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy video-ai-search \
          --image 'gcr.io/glass-oath-344412/video-ai-search:$COMMIT_SHA' \
          --platform managed \
          --region europe-north1

options:
  logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging only for logs