steps:
  # Existing build step (assuming it's in your current directory)
  - name: 'docker'  # Removed "builder" and using just the image name
    args: ['build', '-t', 'video-ai-search:$COMMIT_SHA', '.']

  # Push the image to Container Registry
  - name: 'gcr.io/glass-oath-344412/video-ai-search:$COMMIT_SHA'  # Replace with your details
    args: ['push', 'gcr.io/glass-oath-344412/video-ai-search:$COMMIT_SHA']
    builder: 'docker'

  # Deploy to Cloud Run
  - name: Deploy to Cloud Run
    run: |  # Note the multi-line string syntax
      gcloud run deploy video-ai-search  # Replace with your service name
      --image 'gcr.io/glass-oath-344412/video-ai-search:$COMMIT_SHA'
      --platform managed
      --region europe-north1  # Replace with your desired region